CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_carts_customer FOREIGN KEY (customer_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX uk_carts_customer_active
    ON carts (customer_id)
    WHERE deleted_at IS NULL AND status = 'ACTIVE';

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id),
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity BETWEEN 1 AND 100),
    CONSTRAINT ck_cart_items_unit_price CHECK (unit_price > 0)
);

CREATE UNIQUE INDEX uk_cart_items_cart_product_active
    ON cart_items (cart_id, product_id)
    WHERE deleted_at IS NULL;

CREATE INDEX ix_cart_items_cart_id ON cart_items (cart_id);
