CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(40) NOT NULL,
    customer_id BIGINT NOT NULL,
    assigned_operator_id BIGINT,
    status VARCHAR(30) NOT NULL,
    fulfillment_type VARCHAR(20) NOT NULL,
    total NUMERIC(12, 2) NOT NULL,
    contact_name VARCHAR(160) NOT NULL,
    contact_phone VARCHAR(30) NOT NULL,
    delivery_address VARCHAR(500),
    additional_instructions VARCHAR(1000),
    cancellation_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE,
    preparation_started_at TIMESTAMP WITH TIME ZONE,
    ready_at TIMESTAMP WITH TIME ZONE,
    dispatched_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_orders_assigned_operator FOREIGN KEY (assigned_operator_id) REFERENCES users (id),
    CONSTRAINT ck_orders_total CHECK (total > 0)
);

CREATE INDEX ix_orders_customer_created_at ON orders (customer_id, created_at DESC);
CREATE INDEX ix_orders_status_created_at ON orders (status, created_at DESC);
CREATE INDEX ix_orders_assigned_operator_id ON orders (assigned_operator_id);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_title VARCHAR(160) NOT NULL,
    product_image_url VARCHAR(500),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity BETWEEN 1 AND 100),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price > 0),
    CONSTRAINT ck_order_items_subtotal CHECK (subtotal > 0)
);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);
