CREATE TABLE order_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    previous_status VARCHAR(30),
    current_status VARCHAR(30) NOT NULL,
    details VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_order_audits_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_audits_actor FOREIGN KEY (actor_user_id) REFERENCES users (id)
);

CREATE INDEX ix_order_audits_order_created_at ON order_audits (order_id, created_at, id);
